#pragma once

using namespace ATL;

template <class T>
class CProxy_IWardWizExportsEvents : public IConnectionPointImpl<T, &__uuidof( _IWardWizExportsEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
