; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "WardWiz Antivirus"
#define MyAppVersion "1.8.3.18"
#define MyAppPublisher "WardWiz Antivirus"
#define MyAppURL "http://www.wardwiz.com/"
#define MyAppExeName "WRDWIZUI.EXE"
;Varada Ikhar, Date:13th May-2015, Issue:000283: In control Panel the version no. should not be mentioned. It should be WardWiz Antivirus.
#define MyWardWizAppName "WardWiz"
#define AppVer ReadIni("D:\WardWizDevelopment_1.12\WWBinary.ini", "ProductVersion", "ProductVer", "0.0.0.0")
 
[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{078ABE62-583D-43e6-96D6-5D092883DC82}
AppName={#MyAppName}
AppVersion={#AppVer}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=.\Output
OutputBaseFilename=WardWizEssentialPDB
SetupIconFile=Logo\COMPANYLOGO.ICO
Compression=lzma
SolidCompression=true
;Varada Ikhar, Date:13th May-2015, Issue:000283: In control Panel the version no. should not be mentioned. It should be WardWiz Antivirus.
UninstallDisplayName={#MyWardWizAppName}
UninstallRestartComputer=false
UninstallDisplayIcon={app}\COMPANYLOGO.ICO
UsePreviousAppDir=no
DisableProgramGroupPage=yes
WizardImageFile=SetupImages\setup_img.bmp
WizardSmallImageFile=SetupImages\logo.bmp
AllowCancelDuringInstall=yes
ShowLanguageDialog =no
UseSetupLdr =yes
VersionInfoVersion ={#AppVer}

[Languages]
Name: english; MessagesFile: compiler:Default.isl; LicenseFile: Licence\Enligh-license.txt
Name: German; MessagesFile: compiler:Languages\German.isl; LicenseFile: Licence\Enligh-license.txt
Name: Spanish; MessagesFile: compiler:Languages\Spanish.isl; LicenseFile: Licence\Enligh-license.txt
Name: French; MessagesFile: compiler:Languages\French.isl; LicenseFile: Licence\Enligh-license.txt
;Name: Chinese; MessagesFile: compiler:Languages\Chinese.isl; LicenseFile: Licence\Enligh-license.txt

[LangOptions]
DialogFontSize=8
WelcomeFontName=Verdana
WelcomeFontSize=12
TitleFontName=Arial
TitleFontSize=29
CopyrightFontName=Arial
CopyrightFontSize=8
RightToLeft=no

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Dirs]

[Files]
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\Release\Win32\PDB\*.*; DestDir: {pf}\PDB\32
Source: ..\Release\x64\PDB\*.*; DestDir: {pf}\PDB\64
Source: RequiredFiles\PROTECTION\32\PDB\*.*; DestDir: {pf}\PDB\32
Source: RequiredFiles\PROTECTION\64\PDB\*.*; DestDir: {pf}\PDB\32

[Icons]
Name: {group}\{#MyAppName}; Filename: {app}\{#MyAppExeName}
Name: {group}\{cm:UninstallProgram,{#MyAppName}}; Filename: {uninstallexe}
Name: {commondesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: desktopicon
Name: {userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: quicklaunchicon

[Run]
;neha Gharge nowait remove it will wait till proper installation is not done
Filename: {app}\{#MyAppExeName}; Description: {cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}; Flags: nowait postinstall skipifsilent runascurrentuser

[UninstallRun]
Filename: {app}\WRDWIZCLOSEALL.EXE; Parameters: 

[Registry]

[UninstallDelete]
Type: files; Name: {app}\*.*
Type: filesandordirs; Name: {app}\Log
