#ifndef		_PIPE_CONSTANT_
#define		_PIPE_CONSTANT_

#pragma once

enum {
	START_SCAN		= 1000,
	PAUSE_SCAN,
	RESUME_SCAN,
	STOP_SCAN,
	SCAN_STARTED,
	ANTIROOT_STARTED,
	ANTIROOT_FINISHED,
	SCAN_FINISHED,
	SHOW_VIRUSENTRY,
	HANDLE_VIRUS_ENTRY,
	RECOVER_FILE,
	SAVE_RECOVERDB,
	SHOW_STATUS,
	WRITE_REGISTRY,
	SET_TOTALFILECOUNT,
	RELOAD_DBENTRIES,
	ADD_EMAIL_ENTRY,
	EDIT_EMAIL_ENTRY,
	DELETE_EMAIL_ENTRY,
	SAVE_EMAIL_ENTRIES,
	ADD_FOLDER_LOCKER_ENTRY,
	DELETE_FOLDER_LOCKER_ENTRY,
	SAVE_FOLDER_LOCKER_ENTRY,
	APPLY_FOLDER_LOCKER_SETTING,
	FILE_OPERATIONS,
	START_REGISTRY_OPTIMIZER,
	STOP_REGISTRY_OPTIMIZER,
	REGISTRY_SCAN_FINISHED,
	DELETE_REPORTS_ENTRIES,
	SAVE_REPORTS_ENTRIES,
	ADD_REGISTRATION_DATA,
	ADD_REGISTRATION_DATAINFILE,
	SHOW_EMAILSCAN_TRAY_POPUP,
	RESET_USBSCAN_VARIABLE,
	REPORT_ANTIROOTKIT_ENTRY,
	ENABLE_DISABLE_EMAIL_PLUGIN,
	RELOAD_REGISTARTION_DAYS,
	DELETE_RECOVER_ENTRIES,
	EXIT_APPLICATION,
	START_UPDATE ,
	PAUSE_UPDATE ,
	RESUME_UPDATE ,
	STOP_UPDATE ,
	UPDATE_FINISHED,
	UPDATENOW_POPUP,
	SCAN_FINISHED_SIGNATUREFAILED,
	REPORT_USBSCAN_ENTRY,
	CLOSE_UPDATENOW_POPUP,
	PAUSE_REGISTRY_OPTIMIZER,
	RESUME_REGISTRY_OPTIMIZER,
	RELOAD_SIGNATURE_DATABASE,
	SHOW_RELEASE_NOTES,
	DATA_ENC_DEC_OPERATIONS,
	DATA_ENC_DEC_SHOW_STATUS,
	STOP_CRYPT_OPR,
	PAUSE_CRYPT_OPR,
	RESUME_CRYPT_OPR,
	RELOAD_EMAIL_DB_SETTINGS,
	SETTOTALFILESIZE,
	SETUPDATESTATUS,
	SETMESSAGE,
	SETDOWNLOADPERCENTAGE,
	SHOWSTATUSOFINSTALLATIONDRIVER,
	MEMSCANFINISHED,
	SENDPRODUCTEXPTOTRAY,
	CHECKLIVEUPDATETRAY,
	SCAN_FILE,
	SAVE_LOCALDB,
	SHOWONACCESSPOPUP,
	HANDLEACTICESCANSETTINGS,
	APPLYPRODUCTSETTINGS,
	START_STOP_INDEXING,
	SEND_ACTIVE_PROTECTION_STATUS,
	CLEAR_INDEXING,
	SHOW_SPECUI_PAGE,
	BOOT_SCANNER_OPR,
	SEND_SCHED_SCAN_MISSED,
	RELOAD_WIDGETS_UI,
	START_SCHEDULED_SCAN,
	IS_UI_ANY_TASK_RUNNING,
	SCHEDULED_SCAN_CHANGE,
	LAUNCH_APP_IN_USER_CONTEXT,
	LAUNCH_APPLICATION,
	EPS_INSTALL_SETUP,
	UPDATE_TASK_STATUS,
	SEND_ERROR_LOG,
	SHOW_PASSWORD_WIND,
	SHOW_PC_LOCK_WND,
	SEND_PC_TRAY_LOCK_WND,
	RELOAD_APPLICATION_RULES,
	SEND_PC_TRAY_CLOSE,
	SEND_PC_INET_TRAY_LOCK_WND,
	ON_PC_RESTRICTION,
	ON_INET_RESTRICTION,
	ON_PC_INET_RESTRICT,
	RELOAD_APP_RESTRICTION,
	RELOAD_PACKET_RULES,
	RELOAD_PARENTAL_CONTROL_SETTINGS,
	RELOAD_EMAIL_SCAN_SETTINGS,
	RELOAD_FIREWALL_SETTINGS,
	SHOW_PORT_SCAN_POPUP,
	SHOW_APP_BLOCK_POPUP,
	LAUNCH_APP_USING_SERVICE,
	ON_QUARANTNE_RECOVER,
	RELOAD_WEB_SEC_DB,
	RELOAD_BROWSE_PROT_DB,
	RELOAD_USER_LIST,
	RELOAD_BLOCK_SPEC_WEB_PAGE,
	RELOAD_MNG_EXCLUSION,
	RELOAD_USER_ACESS_LIST,
	SEND_WEBSITE_BLK_NOTIFICATION,
	ON_PC_INITIALISE,
	ON_PC_UNINITIALISE,
	SEND_SCHED_TEMP_FILE_FINISHED,
	SEND_INSTALLER_STATUS_DETAILS,
	SEND_OTHER_AV_DETAILS,
	SEND_USB_AUTOSCAN,
	RELOAD_BROWSER_SEC,
	RELOAD_BROWSER_SEC_EXC,
	RELOAD_BROWSER_SEC_SPEC,
	RELOAD_BROWSER_SECURITY,
	SEND_BROWSER_SECURITY_DETAILS,
	ON_RESET_RESTRICTION,
	ON_BROWSER_SECURITY_UNINITIALIZE,
	ON_CHECK_INTERNET_ACCESS,
	SEND_CLOSE_APP_MSG,
	SEND_INSTALLER_STATUS_SUCCESS,
	UPDATE_REGISTRATION
};

typedef enum {
	RELOAD_FIREWALL_ON_OF,
	RELOAD_FIREWALL_PORT_SCN_REG,
	RELOAD_FIREWALL_STEALTH_MODE_REG,
	RELOAD_FIREWALL_DEF_APP_BEHAVIOR,
}FIREWALL_SETTINGS_TYPE;

typedef enum {
	SZ_STRING,
	SZ_MULSTRING,
	SZ_EXPSTRING,
	SZ_BINARY,
	SZ_DWORD,
}REGISTRY_TYPE;

typedef enum
{
	FILESYSTEMSCAN,
	VIRUSFOUNDENTRY,
	REGISTRYOPTIMIZER,
	ROOTKIT	,
	ALUPDATE
}MEMMAPTYPE;

typedef enum
{
	SETSCANSTATUS,
	SETPERCENTAGE,
	SHOWVIRUSFOUND,
	SHOWTOTALCOUNT,
	SHOWDETECTEDENTRIES,
	DISABLE_CONTROLS
}MEMMAPOPTION;


typedef enum
{
	FILE_PATH_DETAILS,
	UNINSTALL_AV_DETAILS,
	PERCENTAGE_DETAILS,
	FINISH_UNINSTALL_AV_DETAILS,
	SEND_WWIZ_PRODCT_VER,
	FINISH_EXTRACT_FILES,
	INSTALLER_LOCATION_PATH,
	REINSTALL_MSG,
	CHKVER_MSG,
	FINISH_INSTALLATIONS,
	RESERVERD
}INSTALLER_STATUS_CODE;

typedef enum
{
	PEFILESCAN,
	ROOTKITSCAN
}SCANNERTYPE;

//Settings for Active Scan
typedef enum
{
	ENABLEACTSCAN,
	DISABLEACTSCAN
}ACTIVESCANSETTINGS;

//Active Scan Options
typedef enum
{
	DISABLE_FOR_15_MINS,
	DISABLE_FOR_1_HOUR,
	DISABLE_UNTIL_RESTART,
	DISABLE_PERMANANT,
}ACTIVESCANOPTIONS;


//Product Settings options
typedef enum
{
	SHOWTRAYNOTIFICATION,
	AUTOQUARENTINEOPTION,
	ENABLEDISABLESOUND,
	EXCLUDEFILESSCANUPDATED,
	PREPARECACHEINBACKGROUND,
	RELOADSETTINGHEUSCAN,
	SCANBYNAMEFILE,
	RELOAD_EXCLUDE_DB
}PRODUCTSETTINGSOPTIONS;

//Widgets UI options
typedef enum
{
	RELOAD_TEMPORARY_FILES,
	RELOAD_UPDATES,
	RELOAD_PROTECTION_STATUS,
	WIDGET_SHOW_UI,
	WIDGET_HIDE_UI
}WIDGETS_UI_OPTIONS;

typedef enum
{
	USB_AUTO_SCAN_START = 1,
	USB_AUTO_SCAN_END
}USB_SCAN_POPUP_OPTIONS;

#pragma pack(1)
typedef struct
{
	int		iMessageInfo;						//; Message ID
	//HKEY	hHey;								//; Used to send hive
	BYTE	byData[1000];						//; byte data used for Registy type SZ_BINARY
	DWORD	dwValue;							//; Used for Spy ID
	DWORD	dwSecondValue;						//; Used for Spy ID
	TCHAR	szFirstParam[1000];					//; Used for VIRUS_PATH
	TCHAR	szSecondParam[500];					//; Used for VIRUS_NAME
	TCHAR	szThirdParam[500];					//; Used to send REGISTRY VALUEs
}ISPY_PIPE_DATA, *LPISPY_PIPE_DATA;
#pragma pack()


#pragma pack(1)
typedef struct
{
	int		iMessageInfo;
	DWORD	dwFirstValue;
	DWORD	dwSecondValue;
	TCHAR	szFirstParam[MAX_PATH];
	TCHAR	szSecondParam[MAX_PATH];
}ITIN_MEMMAP_DATA, *LPITIN_MEMMAP_DATA;
#pragma pack()

#define		MAPSCANPATH_BUFSIZE		2048
#define		szMapScanPathName		TEXT("Global\\WrdWizMappingScanPath")
#define		szMapRegOptimzerName	TEXT("Global\\WrdWizMapRegOptimzer")
#define		szMapVirFoundEntryName	TEXT("Global\\WrdWizVirusFoundEnry")
#define		szMapRootkitName		TEXT("Global\\WrdWizRootkitName")
#define		szMapALUpdateName		TEXT("Global\\WrdWizALUpadteName")		


//Event Name
#define		szMapScanEventName				TEXT("Global\\WrdWizMappingEventScan")
#define		szMapRegOptimzerEventName		TEXT("Global\\WrdWizMappingEventRegOptimzer")
#define		szMapVirFoundEntryEventName		TEXT("Global\\WrdWizMappingEventVirusFoundEnry")
#define		szMapRootkitEventname			TEXT("Global\\WrdWizMappingEventRootkit")
#define		szMapALUpdateEventName			TEXT("Global\\WrdWizMappingEventALUpdate")	


/*======================================================================================*/
/*								NAMED PIPE NAMES										*/
/*======================================================================================*/
static const TCHAR * SERVICE_SERVER				= L"\\\\.\\pipe\\{AA7D87ADE4A34ac0A23D78E2D83F6058}";
static const TCHAR * AUTOUPDATESRV_SERVER		= L"\\\\.\\pipe\\{F65E10B7468643f6AD94C191D2FE5470}";
static const TCHAR * UI_SERVER					= L"\\\\.\\pipe\\{AE5DBA0235A843e2B9F07E186AC12018}";
static const TCHAR * USB_SERVER					= L"\\\\.\\pipe\\{F935708754CF47d2A70A81D3C67E97D8}";
static const TCHAR * TRAY_SERVER				= L"\\\\.\\pipe\\{808E3A97E5F9424b953FE8C25A63C3F9}";
static const TCHAR * EMAILPLUGIN_SERVER			= L"\\\\.\\pipe\\{13ED3FEFF076485fB64380E5711D81AE}";
static const TCHAR * WWIZ_CRYPT_SERVER			= L"\\\\.\\pipe\\{1C4DBDF653384A6C8F3901BB8158B295}";
static const TCHAR * WWIZ_TROUBLESHOOT_SERVER	= L"\\\\.\\pipe\\{509888266A01446D934325E973E6CE84}";
static const TCHAR * EPS_CLIENT_AGENT			= L"\\\\.\\pipe\\{76C4BF10CDD64C4F94A62B0100574A2D}";
static const TCHAR * WWIZ_INSTALLER_SERVER		= L"\\\\.\\pipe\\{1889C11A9F0045A8B6752D190D0D6735}";
/*======================================================================================*/


#endif