#ifndef _TASKCONSTANTS_
#define _TASKCONSTANTS_

#pragma once

#define WEPS_SERVER_REG_KEY				_T("SOFTWARE\\WardWiz\\WardWizServer")
#define APP_FOLDER_KEY					_T("AppFolder")
#define PARENT_LOG_FOLDER				_T("\\LOG")
#define REMOTE_CLIENT_SERVICE			_T("WardWizDplSrv")
#define REMOTE_CLIENT_SERVICE_FILENAME	_T("\\WRDWIZDPLSRV.EXE")
#define SYSTEM_FOLDER					_T("\\system")
#define IP_SETTINGS_FILE				_T("SERVERINFO.XML")
#define WARDWIZEPSCLIENTX86				_T("WARDWIZEPSCLIENTX86.EXE")
#define WARDWIZEPSCLIENTX64				_T("WARDWIZEPSCLIENTX64.EXE")

enum {
	TASK_SCAN		=	1,
	TASK_EXCHANGE_SCAN,
	TASK_CLIENT_INSTALL,
	TASK_UPGRADE_CLIENT,
	TASK_UNINSTALL_CLIENT,
	TASK_UPDATE_CLIENT,
	TASK_RECONFIGURE_CLIENT,
	TASK_RESTART_MACHINE,
	TASK_NETWORK_DISCOVERY,
	TASK_UPDATE_SECURITY_SERVER,
	APPLY_POLICY
};

enum {
	TASK_PENDING,
	TASK_COMPLETED,
	TASK_IN_PROCESS,
	TASK_FAILD,
};

typedef enum _ERRORS_LOGS
{
	SANITY_CHECK_FAILURE,
	LOGON_FAILURE,
	ERROR_USER_CANCELLED,
	CONNECTION_FAILED
}WARDWIZEPSERRORID;

#endif